services:
  db-a:
    image: "db-a"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mynewdb
  db-b:
    image: "db-b"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mynewdb
networks:
  default:
    name: my_default_network
